import "./globals.css";
// import "antd/dist/reset.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import AntdRegistry from "./AntdRegistry";
import StyledComponentsRegistry from "./StyledComponentsRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NALT App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       { <StyledComponentsRegistry>
          <AntdRegistry>{children}</AntdRegistry>
        </StyledComponentsRegistry>}
      </body>
    </html>
  );
}
